; Jagannath x86-64 Assembly
; Generated by jagc compiler
.intel_syntax noprefix
.text

.global mukhya
.type mukhya, @function
mukhya:
    push rbp
    mov rbp, rsp
.L0:
    ; Assignment
    mov rax, 42
    mov QWORD PTR [rbp-8], rax
    jmp .Lmukhya_epilogue
.Lmukhya_epilogue:
    pop rbp
    ret
.size mukhya, .-mukhya