# Jagannath x86-64 Assembly
# Generated by jagc compiler
.intel_syntax noprefix
.text

.global mukhya
mukhya:
    push rbp
    mov rbp, rsp
    sub rsp, 32
.L0:
    # Assignment
    mov rax, 5
    mov QWORD PTR [rbp-8], rax
    # Assignment
    mov rax, 0
    mov QWORD PTR [rbp-8], rax
    jmp .Lmukhya_epilogue
.Lmukhya_epilogue:
    add rsp, 32
    pop rbp
    ret