; Jagannath x86-64 Assembly
; Generated by jagc compiler
.intel_syntax noprefix
.text

.global phiḍabanāci
.type phiḍabanāci, @function
phiḍabanāci:
    push rbp
    mov rbp, rsp
    ; Save r15 (kartṛ - agent)
    push r15
    sub rsp, 64
    ; Store arg 0 from rdi
    mov QWORD PTR [rbp-72], rdi
.L0:
    ; Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, 1
    cmp rcx, rdx
    setle al
    movzx rax, al
    mov QWORD PTR [rbp-16], rax
    ; Switch on discriminant
    mov rax, QWORD PTR [rbp-16]
    cmp rax, 1
    je .L1
    jmp .L2
.L1:
    ; Assignment
    mov rax, QWORD PTR [rbp-8]
    mov QWORD PTR [rbp-8], rax
    jmp .L3
.L2:
    jmp .L3
.L3:
    ; Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, 1
    mov rax, rcx
    sub rax, rdx
    mov QWORD PTR [rbp-24], rax
    ; Function call
    mov rdi, QWORD PTR [rbp-24]
    call phiḍabanāci
    mov QWORD PTR [rbp-32], rax
    jmp .L4
.L4:
    ; Assignment
    mov rax, QWORD PTR [rbp-32]
    mov QWORD PTR [rbp-40], rax
    ; Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, 2
    mov rax, rcx
    sub rax, rdx
    mov QWORD PTR [rbp-48], rax
    ; Function call
    mov rdi, QWORD PTR [rbp-48]
    call phiḍabanāci
    mov QWORD PTR [rbp-56], rax
    jmp .L5
.L5:
    ; Assignment
    mov rax, QWORD PTR [rbp-56]
    mov QWORD PTR [rbp-64], rax
    ; Assignment
    mov rcx, QWORD PTR [rbp-40]
    mov rdx, QWORD PTR [rbp-64]
    mov rax, rcx
    add rax, rdx
    mov QWORD PTR [rbp-8], rax
    jmp .Lphiḍabanāci_epilogue
.Lphiḍabanāci_epilogue:
    add rsp, 64
    pop r15
    pop rbp
    ret
.size phiḍabanāci, .-phiḍabanāci
.global phiḍabanāci_pariṣkṛta
.type phiḍabanāci_pariṣkṛta, @function
phiḍabanāci_pariṣkṛta:
    push rbp
    mov rbp, rsp
    ; Save r14 (kartṛ - agent)
    push r14
    sub rsp, 64
    ; Store arg 0 from rdi
    mov QWORD PTR [rbp-64], rdi
.L0:
    ; Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, 0
    cmp rcx, rdx
    sete al
    movzx rax, al
    mov QWORD PTR [rbp-16], rax
    ; Switch on discriminant
    mov rax, QWORD PTR [rbp-16]
    cmp rax, 1
    je .L1
    jmp .L2
.L1:
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-8], rax
    jmp .L3
.L2:
    jmp .L3
.L3:
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-24], rax
    ; Assignment
    mov rax, 1
    mov QWORD PTR [rbp-32], rax
    ; Assignment
    mov rax, 1
    mov QWORD PTR [rbp-40], rax
    jmp .L4
.L4:
    ; Assignment
    mov rcx, QWORD PTR [rbp-40]
    mov rdx, QWORD PTR [rbp-8]
    cmp rcx, rdx
    setl al
    movzx rax, al
    mov QWORD PTR [rbp-48], rax
    ; Switch on discriminant
    mov rax, QWORD PTR [rbp-48]
    cmp rax, 1
    je .L5
    jmp .L6
.L5:
    ; Assignment
    mov rcx, QWORD PTR [rbp-24]
    mov rdx, QWORD PTR [rbp-32]
    mov rax, rcx
    add rax, rdx
    mov QWORD PTR [rbp-56], rax
    ; Assignment
    mov rcx, QWORD PTR [rbp-40]
    mov rdx, 1
    mov rax, rcx
    add rax, rdx
    mov QWORD PTR [rbp-40], rax
    jmp .L4
.L6:
    ; Assignment
    mov rax, QWORD PTR [rbp-32]
    mov QWORD PTR [rbp-8], rax
    jmp .Lphiḍabanāci_pariṣkṛta_epilogue
.Lphiḍabanāci_pariṣkṛta_epilogue:
    add rsp, 64
    pop r14
    pop r15
    pop rbp
    ret
.size phiḍabanāci_pariṣkṛta, .-phiḍabanāci_pariṣkṛta
.global mukhya
.type mukhya, @function
mukhya:
    push rbp
    mov rbp, rsp
    sub rsp, 48
.L0:
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-8], rax
    jmp .L1
.L1:
    ; Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, 20
    cmp rcx, rdx
    setl al
    movzx rax, al
    mov QWORD PTR [rbp-16], rax
    ; Switch on discriminant
    mov rax, QWORD PTR [rbp-16]
    cmp rax, 1
    je .L2
    jmp .L3
.L2:
    ; Function call
    mov rdi, QWORD PTR [rbp-8]
    call phiḍabanāci_pariṣkṛta
    mov QWORD PTR [rbp-32], rax
    jmp .L4
.L4:
    ; Assignment
    mov rax, QWORD PTR [rbp-32]
    mov QWORD PTR [rbp-24], rax
    ; Function call
    call mudraṇa
    mov QWORD PTR [rbp-40], rax
    jmp .L5
.L5:
    ; Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, 1
    mov rax, rcx
    add rax, rdx
    mov QWORD PTR [rbp-8], rax
    jmp .L1
.L3:
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-8], rax
    jmp .Lmukhya_epilogue
.Lmukhya_epilogue:
    add rsp, 48
    pop r14
    pop r15
    pop rbp
    ret
.size mukhya, .-mukhya