; Jagannath x86-64 Assembly
; Generated by jagc compiler
.intel_syntax noprefix
.text

.global mukhya
.type mukhya, @function
mukhya:
    push rbp
    mov rbp, rsp
    sub rsp, 16
.L0:
    ; Function call
    mov rax, 0
    call rax
    mov QWORD PTR [rbp-8], rax
    jmp .L1
.L1:
    ; Function call
    mov rax, 0
    call rax
    mov QWORD PTR [rbp-16], rax
    jmp .L2
.L2:
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-8], rax
    jmp .Lmukhya_epilogue
.Lmukhya_epilogue:
    add rsp, 16
    pop rbp
    ret
.size mukhya, .-mukhya