; Jagannath x86-64 Assembly
; Generated by jagc compiler
.intel_syntax noprefix
.text

.global count
.type count, @function
count:
    push rbp
    mov rbp, rsp
    sub rsp, 32
.L0:
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-8], rax
    ; Assignment
    mov rax, 0
    mov QWORD PTR [rbp-16], rax
    jmp .L1
.L1:
    ; Assignment
    mov rcx, QWORD PTR [rbp-16]
    mov rdx, 10
    cmp rcx, rdx
    setl al
    movzx rax, al
    mov QWORD PTR [rbp-24], rax
    ; Switch on discriminant
    mov rax, QWORD PTR [rbp-24]
    cmp rax, 1
    je .L2
    jmp .L3
.L2:
    ; Assignment
    mov rcx, QWORD PTR [rbp-16]
    mov rdx, 1
    mov rax, rcx
    add rax, rdx
    mov QWORD PTR [rbp-16], rax
    jmp .L1
.L3:
    ; Assignment
    mov rax, QWORD PTR [rbp-8]
    mov QWORD PTR [rbp-8], rax
    jmp .Lcount_epilogue
.Lcount_epilogue:
    add rsp, 32
    pop rbp
    ret
.size count, .-count