# Jagannath x86-64 Assembly
# Generated by jagc compiler
.intel_syntax noprefix
.text

.global max
max:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    # Store arg 0 from rdi
    mov QWORD PTR [rbp-32], rdi
    # Store arg 1 from rsi
    mov QWORD PTR [rbp-40], rsi
.L0:
    # Assignment
    mov rcx, QWORD PTR [rbp-8]
    mov rdx, QWORD PTR [rbp-16]
    cmp rcx, rdx
    setg al
    movzx rax, al
    mov QWORD PTR [rbp-24], rax
    # Switch on discriminant
    mov rax, QWORD PTR [rbp-24]
    cmp rax, 1
    je .L1
    jmp .L2
.L1:
    # Assignment
    mov rax, QWORD PTR [rbp-8]
    mov QWORD PTR [rbp-8], rax
    jmp .L3
.L2:
    # Assignment
    mov rax, QWORD PTR [rbp-16]
    mov QWORD PTR [rbp-8], rax
    jmp .L3
.L3:
    jmp .Lmax_epilogue
.Lmax_epilogue:
    add rsp, 32
    pop rbp
    ret